kumuluzee:
  name: ratings
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/RatingsDS
      connection-url: jdbc:postgresql://192.168.99.100:5433/rating
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/RatingsDS
  rest-properties:
  healthy: true

